terriamap:
    serverConfig:
        port: 3001
        allowProxyFor: [
            "nicta.com.au",
            "gov.au",
            "csiro.au",
            "arcgis.com",
            "argo.jcommops.org",
            "www.abc.net.au",
            "geoserver.aurin.org.au",
            "mapsengine.google.com",
            "s3-ap-southeast-2.amazonaws.com",
            "adelaidecitycouncil.com",
            "www.dptiapps.com.au",
            "geoserver-123.aodn.org.au",
            "geoserver.imos.org.au",
            "nci.org.au",
            "static.nationalmap.nicta.com.au",
            "githubusercontent.com",
            "gov",
            "gov.uk",
            "gov.nz",
            "sample.aero3dpro.com.au"
        ]
        initPaths:
        - "/etc/config/client"
        newShareUrlPrefix: "s"
        shareUrlPrefixes:
            s:
                service: "s3"
                region: "ap-southeast-2"
                bucket: "terriajs-ci-sharing"
                accessKeyId: "secret"
                secretAccessKey: "secret"
        feedback:
            userAgent: TerriaBot (TerriaJS Feedback)
            issuesUrl: https://api.github.com/repos/TerriaJS/demo-feedback/issues
            accessToken: secret
    clientConfig:
        initializationUrls:
        - simple
        parameters:
            bingMapsKey: "AiGfmTpmtbNIRJER8VKGKZMFZ4mGISCy4XS-Bvzb64IE3D0ILZpYorFHShd2AX8U"
            cesiumIonAccessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxZDY5MDE1YS0yNGFlLTQ1MzctYWNkNy0wNDQ1YWNiNTM5MDIiLCJpZCI6Mjk5Miwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTUzODAzMzgyNn0.a2uTotdiHUo8FiHsO4MVNZ1KT5pOF0rb7CFdwbRAsOo"
            googleAnalyticsKey:
            disclaimer:
                text: "Disclaimer: This map must not be used for navigation or precise spatial analysis"
                url: "https://terria.io"
            developerAttribution:
                text: "Terria"
                link: "https://terria.io"
            appName: "TerriaJS Continuous Integration"
            brandBarElements: ["", "<a target=\"_blank\" href=\"http://terria.io\"><img src=\"images/terria_logo.png\" height=\"52\" title=\"Version: {{version}}\" /></a>", ""]
            supportEmail: "info@terria.io"
            mobileDefaultViewerMode: "2d"
            experimentalFeatures: true
            feedbackUrl: "feedback"
            helpContent: 
                - 
                  title: "Getting started with the map"
                  itemName: gettingstarted
                  markdownText: "# Getting started with the map\n\nIf you''re new to the map or using spatial data, our Getting Started video quickly covers the basic functionality you''ll need to use to add and interrogate data sets.\n\nIf you don''t have time to watch the video, we suggest exploring the following areas:\n\n1. Search for a location to quickly find an area of interest\n2. Use ''Explore map data'' to view the catalogue of available data sets and add them to the map\n3. Interact with the data layer, including opacity and toggling on and off on the left in your workbench\n4. Click on the data on the map to view more detailed data, including the raw data\n5. Change your basemap using options in ''Map Settings'' to help make some data sets more visible\n6. Zoom and change your view, including tilting the view angle using the controls on the right-hand side of the screen"
                  icon: "video"
                  videoUrl: "https://www.youtube.com/embed/FjSxaviSLhc"
                  placeholderImage: "https://img.youtube.com/vi/FjSxaviSLhc/maxresdefault.jpg"
                -
                  title: Step by step guide
                  itemName: stepbystepguide
                  paneMode: trainer
                  icon: "oneTwoThree"
                  markdownText: "# Step by step guide\n\nLaunch a step by step guide for various popular workflows below:"
                  trainerItems:
                    - title: Adding satellite imagery
                      footnote: "Important: Satellite imagery can take a little while to load so please be patient. If images don’t seem to be loading, zoom out a little bit"
                      steps:
                      - title: Find a location to view satellite imagery
                        markdownDescription: "- Use the location search or zoom and pan around the map
                          using your mouse or the zoom controls"
                      - title: Find satellite images in the data catalogue using "Add Data" button
                        markdownDescription: |-
                          - Click "Explore map data" and navigate to Satellite images and press "Add Data"
                          - Select your satellite option: Landsat or Sentinel, what resolution and daily or composite images. This can depend on resolution of the image you need (10m or 25m) and whether you want daily, 16 day composite, or annual average images
                      - title: Filter images to find satellite imagery
                        markdownDescription: |-
                          - Filter images by location to quickly find satellite images for that location
                            - Satellites circle the globe many times a day. You can expect satellite imagery to be available for one location every two weeks
                            - If you haven''t already selected your point of interest on the map, zoom in to select one. You will see the filter applied in blue in the Workbench on the left
                      - title: Select a time and date
                        markdownDescription: |-
                          - Use the date picker to select a time and date. Cycle backwards through previous years using the back arrow
                            - Choose another date if your imagery is obscured by cloud. You can quickly cycle back and forward using the arrows next to the date picker
                    - title: View and compare time-series data
                      footnote: "Important: Any time series data can be compared using the Split Screen Mode, not just satellite imagery"
                      steps:
                      - title: Add a time series data set to the map
                        markdownDescription: |-
                          - Satellite imagery is a good example of time series data, with many satellites going back decades
                          - Find your location of interest and filter available imagery by this location
                          -See our Adding Satellite Imagery to the Map guide for more
                      - title: Select the time and date
                        markdownDescription: |-
                          - In the workbench on the left, select the time and date which will open the date picker
                          - Select a year, month and date, or navigate back to other years and even centuries using the back arrow
                          - Available dates appear in blue
                      - title: Compare different dates at one location
                        markdownDescription: |-
                          - From the 3 dots drop-down menu in the workbench, press ''Compare'' to activate Split Screen Mode
                          - A duplicate copy of your dataset will appear in the workbench
                          - Choose the dates you want to compare on the left and right of the screen
                          - Drag the slider using the white button to swipe and compare the two image dates
                      - title: Close Split Screen Mode
                        markdownDescription: |-
                          - Escape the Split Screen Mode by pressing the ''x'' of Split Screen Mode title in the workbench
                          - Remove the duplicate copy of your dataset in the workbench using the 3 dots drop-down menu
                    - title: Detecting the change (difference) between data values at two points in time
                        (e.g. NDVI or Burn Extent)
                      steps:
                      - title: Add a Difference-enabled dataset to the map
                        markdownDescription: |-
                          - This includes the dataset Delta Blended Service
                          - Search or scroll to find the location where you want to perform change detection
                      - title: Turn on Difference mode
                        markdownDescription: |-
                          -   Behind the 3 dots in the workbench, select the menu item ''Difference''
                          -   Difference mode will activate, splitting the screen and adding new options on the left
                      - title: Select your Difference variables
                        markdownDescription: |-
                          -   Use the date pickers at the bottom to choose your dates for screen A and B
                            -   The Preview style defaults to True colour to help you find cloud-free images, change if required
                            -   If you have previously searched for a location, this will be used to refine the imagery to only show available images for that location
                            -   If you didn''t search for a location, select a point on the map in your area of interest to refine the imagery for that area only
                            -   Select your Difference Output, e.g. NDVI
                            -   Select Generate Change Detection
                      - title: View the change detection results on-screen
                        markdownDescription: |-
                          -   The legend for the Difference calculation will appear on the left to help your analysis
                            -   You can change dates using the date pickers to toggle between dates and a new Change Detection calculation will be run
                            -   Close or exit Difference mode when you are finished your analysis
                    
    resources:
        requests:
            cpu: 10m
            memory: 10Mi
